// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebsiteAPI.Data;

namespace WebsiteAPI.Migrations
{
    [DbContext(typeof(OutletContext))]
    [Migration("20210119054030_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("WebsiteAPIotnet .Models.Outlet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Landmark")
                        .HasColumnType("text");

                    b.Property<int>("No_of_AvaiFoodItems")
                        .HasColumnType("integer");

                    b.Property<int>("OrderDate")
                        .HasColumnType("integer");

                    b.Property<string>("OutletName")
                        .HasColumnType("text");

                    b.Property<int>("Req_Volunteer")
                        .HasColumnType("integer");

                    b.Property<string>("StreetName")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Outlets");
                });
#pragma warning restore 612, 618
        }
    }
}
